[project]
name = "airflow-jobs"
version = "0.1.0"
description = "ETL pipeline for Data Fusion Module"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.6.1",
    "pandas>=3.0.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.46",
]
